[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_post_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/deol.nvim'


