
## hook の種類
# https://qiita.com/delphinus/items/cd221a450fd23506e81a
# hook の名前       実行されるタイミング                          lazy OFF  lazy ON
# hook_add          プラグインが dein.vim によって追加されたとき  OK        OK
# hook_source       プラグインが読み込まれる直前                  NG        OK
# hook_post_source  プラグインが読み込まれた直後                  NG        OK
# hook_post_update  プラグインが更新された直後                    OK        OK
#####
# :h dein-options
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'tomasr/molokai'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme molokai
'''

[[plugins]]
repo = 'jiangmiao/auto-pairs'
on_i = 1

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_post_source = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/deol.nvim'


